// backend/prisma/seed.js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

// Sua lista de 366 versículos deve estar aqui
const verses = [
  // Seus pedidos
  { month: 1, day: 1, verseText: "Entrem por suas portas com ações de graças e, em seus pátios, com cânticos de louvor; deem-lhe graças e louvem o seu nome.", verseReference: "Salmos 100:4", version: "NVT" },
  { month: 1, day: 2, verseText: "Somente seja forte e muito corajoso! Tenha o cuidado de obedecer a toda a lei que o meu servo Moisés lhe ordenou; não se desvie dela, nem para a direita nem para a esquerda, para que você seja bem sucedido por onde quer que andar.", verseReference: "Josué 1:7", version: "ACF" },
  { month: 1, day: 3, verseText: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?", verseReference: "Salmos 27:1", version: "ACF" },
  { month: 1, day: 4, verseText: "Toda a lei se resume num só mandamento: \"Ame o seu próximo como a si mesmo\".", verseReference: "Gálatas 5:14", version: "NVI" },
  { month: 1, day: 5, verseText: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.", verseReference: "Mateus 6:33", version: "NVI" },
  { month: 1, day: 6, verseText: "No entanto, está chegando a hora, e de fato já chegou, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade. São estes os adoradores que o Pai procura.", verseReference: "João 4:23", version: "NVI" },
  { month: 1, day: 7, verseText: "Meus filhinhos, escrevo-lhes estas coisas para que vocês não pequem. Se, porém, alguém pecar, temos um intercessor junto ao Pai, Jesus Cristo, o Justo.", verseReference: "1 João 2:1", version: "NVI" },
  { month: 1, day: 8, verseText: "Apeguemo-nos com firmeza à esperança que professamos, pois aquele que prometeu é fiel.", verseReference: "Hebreus 10:23", version: "NVI" },
  { month: 1, day: 9, verseText: "o Senhor faça resplandecer o seu rosto sobre ti e te conceda graça;", verseReference: "Números 6:25", version: "NVI" },
  { month: 1, day: 10, verseText: "Conseqüentemente, a fé vem por ouvir a mensagem, e a mensagem é ouvida mediante a palavra de Cristo.", verseReference: "Romanos 10:17", version: "NVI" },
  { month: 1, day: 11, verseText: "Não deixe de falar as palavras deste Livro da Lei e de meditar nelas de dia e de noite, para que você cumpra fielmente tudo o que nele está escrito. Só então os seus caminhos prosperarão e você será bem sucedido.", verseReference: "Josué 1:8", version: "NVI" },
  { month: 1, day: 12, verseText: "Dei-lhes, entretanto, esta ordem: Obedeçam-me, e eu serei o seu Deus e vocês serão o meu povo. Vocês andarão em todo o caminho que eu lhes ordenar, para que tudo lhes vá bem.", verseReference: "Jeremias 7:23", version: "NVI" },
  { month: 1, day: 13, verseText: "Busquem o Senhor enquanto se pode achá-lo; clamem por ele enquanto está perto.", verseReference: "Isaías 55:6", version: "NVI" },
  { month: 1, day: 14, verseText: "Alegrem-se sempre no Senhor. Repito: alegrem-se!", verseReference: "Filipenses 4:4", version: "NVT" },
  { month: 1, day: 15, verseText: "Será inútil levantar cedo e dormir tarde, trabalhando arduamente por alimento. O Senhor concede o sono àqueles a quem ama.", verseReference: "Salmos 127:2", version: "NVI" },
  { month: 1, day: 16, verseText: "Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.", verseReference: "Tiago 1:5", version: "NVI" },
  { month: 1, day: 17, verseText: "Agora lhes pedimos, irmãos, que tenham consideração para com os que se esforçam no trabalho entre vocês, que os lideram no Senhor e os aconselham.", verseReference: "1 Tessalonicenses 5:12", version: "NVI" },
  { month: 1, day: 18, verseText: "Dediquem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a si próprios.", verseReference: "Romanos 12:10", version: "NVI" },
  { month: 1, day: 19, verseText: "Tu, porém, és o Santo, és rei, és o louvor de Israel.", verseReference: "Salmos 22:3", version: "NVI" },
  { month: 1, day: 20, verseText: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", verseReference: "Salmos 91:1", version: "ACF" },
  { month: 1, day: 21, verseText: "Louvado seja o Senhor! Louvem o Senhor em seu santuário, louvem-no em seu majestoso céu!", verseReference: "Salmos 150:1", version: "NVT" },
  { month: 1, day: 22, verseText: "Aquele que é a Palavra tornou-se carne e viveu entre nós. Vimos a sua glória, glória como do Unigênito vindo do Pai, cheio de graça e de verdade.", verseReference: "João 1:14", version: "NVI" },
  { month: 1, day: 23, verseText: "Fuja dos desejos malignos da juventude e siga a justiça, a fé, o amor e a paz, juntamente com os que, de coração puro, invocam o Senhor.", verseReference: "2 Timóteo 2:22", version: "NVI" },
  { month: 1, day: 24, verseText: "A vereda do justo evita o mal; quem guarda o seu caminho preserva a sua vida.", verseReference: "Provérbios 16:17", version: "NVI" },
  { month: 1, day: 25, verseText: "Mas quem é você, ó homem, para questionar a Deus? \"Acaso aquilo que é formado pode dizer ao que o formou: ‘Por que me fizeste assim? ’ \"", verseReference: "Romanos 9:20", version: "NVI" },
  { month: 1, day: 26, verseText: "Tudo que respira louve ao Senhor! Louvado seja o Senhor!", verseReference: "Salmos 150:6", version: "NVT" },
  { month: 1, day: 27, verseText: "Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.", verseReference: "Romanos 5:8", version: "NVI" },
  { month: 1, day: 28, verseText: "\"Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dá muito fruto; pois sem mim vocês não podem fazer coisa alguma.", verseReference: "João 15:5", version: "NVI" },
  { month: 1, day: 29, verseText: "Pois, quem dentre os homens conhece as coisas do homem, a não ser o espírito do homem que nele está? Da mesma forma, ninguém conhece as coisas de Deus, a não ser o Espírito de Deus.", verseReference: "1 Coríntios 2:11", version: "NVI" },
  { month: 1, day: 30, verseText: "Sejam completamente humildes e dóceis, e sejam pacientes, suportando uns aos outros com amor.", verseReference: "Efésios 4:2", version: "NVI" },
  { month: 1, day: 31, verseText: "A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.", verseReference: "Colossenses 3:16", version: "ARC" },
  { month: 2, day: 1, verseText: "Direi do Senhor: Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei.", verseReference: "Salmos 91:2", version: "ACF" },
  { month: 2, day: 2, verseText: "Jesus respondeu: \"Eu lhes asseguro que, se vocês tiverem fé e não duvidarem, poderão fazer não somente o que foi feito à figueira, mas também dizer a este monte: ‘Levante-se e atire-se no mar’, e assim será feito.", verseReference: "Mateus 21:21", version: "NVI" },
  { month: 2, day: 3, verseText: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.", verseReference: "Romanos 12:2", version: "NVI" },
  { month: 2, day: 4, verseText: "Sirvam ao Senhor com alegria, apresentem-se diante dele com cânticos.", verseReference: "Salmos 100:2", version: "NVT" },
  { month: 2, day: 5, verseText: "Por isso, por meio de Jesus Cristo, ofereçamos sempre louvor a Deus. Esse louvor é o sacrifício que apresentamos, a oferta que é dada por lábios que confessam a sua fé nele.", verseReference: "Hebreus 13:5", version: "NTLH" },
  { month: 2, day: 6, verseText: "Tomem sobre vocês o meu jugo e aprendam de mim, pois sou manso e humilde de coração, e vocês encontrarão descanso para as suas almas.", verseReference: "Mateus 11:29", version: "NVI" },
  { month: 2, day: 7, verseText: "As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim;", verseReference: "Lamentações de Jeremias 3:22", version: "ACF" },
  { month: 2, day: 8, verseText: "Porque sou eu que conheço os planos que tenho para vocês\", diz o Senhor, \"planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro.", verseReference: "Jeremias 29:11", version: "NVI" },
  { month: 2, day: 9, verseText: "Mas agora, em Cristo Jesus, vocês, que antes estavam longe, foram aproximados mediante o sangue de Cristo.", verseReference: "Efésios 2:13", version: "NVI" },
  { month: 2, day: 10, verseText: "Louvem o Senhor todas as nações; louvem-no todos os povos.", verseReference: "Salmos 117:1", version: "NVT" },
  { month: 2, day: 11, verseText: "Apegue-se à instrução, não a abandone; guarde-a bem, pois dela depende a sua vida.", verseReference: "Provérbios 4:13", version: "NVI" },
  { month: 2, day: 12, verseText: "Aleluia! Louve, ó minha alma, o Senhor.", verseReference: "Salmos 146:1", version: "NAA" },
  { month: 2, day: 13, verseText: "Venham, cantemos ao Senhor com júbilo, celebremos o Rochedo da nossa salvação.", verseReference: "Salmos 95:1", version: "NAA" },
  { month: 2, day: 14, verseText: "Este é o Deus cujo caminho é perfeito; a palavra do Senhor é comprovadamente genuína. Ele é um escudo para todos os que nele se refugiam.", verseReference: "Salmos 18:30", version: "NVI" },
  { month: 2, day: 15, verseText: "Louvem eles o seu nome com danças; ofereçam-lhe música com tamborim e harpa.", verseReference: "Salmos 149:3", version: "NVI" },
  { month: 2, day: 16, verseText: "Tirou-me de um poço de perdição, de um tremedal de lama; colocou os meus pés sobre uma rocha e firmou os meus passos.", verseReference: "Salmos 40:2", version: "ACF" },
  { month: 2, day: 17, verseText: "Louvem-no com tamborins e danças, louvem-no com instrumentos de cordas e flautas!", verseReference: "Salmos 150:4", version: "NVT" },
  { month: 2, day: 18, verseText: "Mas ele foi transpassado por causa das nossas transgressões, foi esmagado por causa de nossas iniqüidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados.", verseReference: "Isaías 53:5", version: "NVI" },
  { month: 2, day: 19, verseText: "Então Davi e todo o povo começaram a dançar com todas as suas forças em louvor a Deus. Eles cantavam e tocavam instrumentos musicais, isto é, harpas, liras, tambores, pratos e trombetas.", verseReference: "1 Crônicas 13:8", version: "NTLH" },
  { month: 2, day: 20, verseText: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores.", verseReference: "Salmos 1:1", version: "ACF" },
  { month: 2, day: 21, verseText: "Bendiga, minha alma, o Senhor, e tudo o que há em mim bendiga o seu santo nome.", verseReference: "Salmos 103:1", version: "NAA" },
  { month: 2, day: 22, verseText: "Não só isso, mas também nos gloriamos nas tribulações, porque sabemos que a tribulação produz perseverança;", verseReference: "Romanos 5:3", version: "NVI" },
  { month: 2, day: 23, verseText: "Não deixemos de reunir-nos como igreja, segundo o costume de alguns, mas encorajemo-nos uns aos outros, ainda mais quando vocês vêem que se aproxima o Dia.", verseReference: "Hebreus 10:25", version: "NVI" },
  { month: 2, day: 24, verseText: "Deus é espírito, e é necessário que os seus adoradores o adorem em espírito e em verdade\".", verseReference: "João 4:24", version: "NVI" },
  { month: 2, day: 25, verseText: "Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.", verseReference: "1 Tessalonicenses 5:18", version: "NVI" },
  { month: 2, day: 26, verseText: "Cantarei a lealdade e a justiça. A ti, Senhor, cantarei louvores!", verseReference: "Salmos 101:1", version: "NVI" },
  { month: 2, day: 27, verseText: "\"Tudo é permitido\", mas nem tudo convém. \"Tudo é permitido\", mas nem tudo edifica.", verseReference: "1 Coríntios 10:23", version: "NVI" },
  { month: 2, day: 28, verseText: "Portanto, também nós, uma vez que estamos rodeados por tão grande nuvem de testemunhas, livremo-nos de tudo o que nos atrapalha e do pecado que nos envolve, e corramos com perseverança a corrida que nos é proposta,", verseReference: "Hebreus 12:1", version: "NVI" },
  { month: 2, day: 29, verseText: "Porque a vontade de meu Pai é que todo o que olhar para o Filho e nele crer tenha a vida eterna, e eu o ressuscitarei no último dia\".", verseReference: "João 6:40", version: "NVI" },
  { month: 3, day: 1, verseText: "Rendam graças ao Senhor, pois ele é bom; o seu amor dura para sempre.", verseReference: "1 Crônicas 16:34", version: "NVI" },
  { month: 3, day: 2, verseText: "Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza.", verseReference: "Salmos 139:14", version: "NVI" },
  { month: 3, day: 3, verseText: "Então conheçamos, e prossigamos em conhecer ao Senhor; a sua saída, como a alva, é certa; e ele a nós virá como a chuva, como chuva serôdia que rega a terra.", verseReference: "Oséias 6:3", version: "ACF" },
  { month: 3, day: 4, verseText: "Ele te cobrirá com as suas penas, e debaixo das suas asas te confiarás; a sua verdade será o teu escudo e broquel.", verseReference: "Salmos 91:4", version: "ACF" },
  { month: 3, day: 5, verseText: "Pois grande é o seu amor por nós; a fidelidade do Senhor dura para sempre. Louvado seja o Senhor!", verseReference: "Salmos 117:2", version: "NVT" },
  { month: 3, day: 6, verseText: "² Louvarei o Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto eu viver.", verseReference: "Salmos 146:2", version: "NAA" },
  { month: 3, day: 7, verseText: "Porque somos criação de Deus realizada em Cristo Jesus para fazermos boas obras, as quais Deus preparou de antemão para que nós as praticássemos.", verseReference: "Efésios 2:10", version: "NVI" },
  { month: 3, day: 8, verseText: "Durante os seus dias de vida na terra, Jesus ofereceu orações e súplicas, em alta voz e com lágrimas, àquele que o podia salvar da morte, sendo ouvido por causa da sua reverente submissão.", verseReference: "Hebreus 5:7", version: "NVI" },
  { month: 3, day: 9, verseText: "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus;", verseReference: "Efésios 2:8", version: "NVI" },
  { month: 3, day: 10, verseText: "O SENHOR é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam,", verseReference: "Naum 1:7", version: "NVI" },
  { month: 3, day: 11, verseText: "Vamos à presença dele com ações de graças; vamos aclamá-lo com cânticos de louvor.", verseReference: "Salmos 95:2", version: "NVI" },
  { month: 3, day: 12, verseText: "Cantai ao Senhor um cântico novo, cantai ao Senhor toda a terra", verseReference: "Salmos 96:1", version: "ACF" },
  { month: 3, day: 13, verseText: "Bendiga, minha alma, o Senhor, e não se esqueça de nem um só de seus benefícios.", verseReference: "Salmos 103:2", version: "NAA" },
  { month: 3, day: 14, verseText: "Adorem o Senhor com temor; exultem com tremor.", verseReference: "Salmos 2:11", version: "NVI" },
  { month: 3, day: 15, verseText: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", verseReference: "Romanos 12:12", version: "NVI" },
  { month: 3, day: 16, verseText: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", verseReference: "Hebreus 11:1", version: "NVI" },
  { month: 3, day: 17, verseText: "O conselho da sabedoria é: procure obter sabedoria; use tudo que você possui para adquirir entendimento.", verseReference: "Provérbios 4:7", version: "NVI" },
  { month: 3, day: 18, verseText: "Assim sendo, aproximemo-nos do trono da graça com toda a confiança, a fim de recebermos misericórdia e encontrarmos graça que nos ajude no momento da necessidade.", verseReference: "Hebreus 4:16", version: "NVI" },
  { month: 3, day: 19, verseText: "Não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê: primeiro do judeu, depois do grego.", verseReference: "Romanos 1:16", version: "NVI" },
  { month: 3, day: 20, verseText: "Mas agora, Senhor, tu és o nosso Pai. Nós somos o barro, e tu és o nosso oleiro; e todos nós somos obra das tuas mãos.", verseReference: "Isaías 64:8", version: "NAA" },
  { month: 3, day: 21, verseText: "Finalmente, irmãos, tudo o que for verdadeiro, tudo o que for nobre, tudo o que for correto, tudo o que for puro, tudo o que for amável, tudo o que for de boa fama, se houver algo de excelente ou digno de louvor, pensem nessas coisas.", verseReference: "Filipenses 4:8", version: "NVI" },
  { month: 3, day: 22, verseText: "Disse Jesus: \"A minha comida é fazer a vontade daquele que me enviou e concluir a sua obra.", verseReference: "João 4:34", version: "NVI" },
  { month: 3, day: 23, verseText: "Jesus respondeu: \"A obra de Deus é esta: crer naquele que ele enviou\".", verseReference: "João 6:29", version: "NVI" },
  { month: 3, day: 24, verseText: "Como suspira a corça pelas correntes das águas, assim, por ti, ó Deus, suspira a minha alma.", verseReference: "Salmos 42:1", version: "ARA" },
  { month: 3, day: 25, verseText: "mas aqueles que esperam no Senhor renovam as suas forças. Voam bem alto como águias; correm e não ficam exaustos, andam e não se cansam.", verseReference: "Isaías 40:31", version: "NVI" },
  { month: 3, day: 26, verseText: "Assim também a fé, por si só, se não for acompanhada de obras, está morta.", verseReference: "Tiago 2:17", version: "NVI" },
  { month: 3, day: 27, verseText: "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.", verseReference: "Salmos 37:4", version: "ACF" },
  { month: 3, day: 28, verseText: "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens,", verseReference: "Colossenses 3:23", version: "NVI" },
  { month: 3, day: 29, verseText: "Se alguém se purificar dessas coisas, será vaso para honra, santificado, útil para o Senhor e preparado para toda boa obra.", verseReference: "2 Timóteo 2:21", version: "NVI" },
  { month: 3, day: 30, verseText: "Pois virá o tempo em que não suportarão a sã doutrina; pelo contrário, sentindo coceira nos ouvidos, segundo os seus próprios desejos juntarão mestres para si mesmos.", verseReference: "2 Timóteo 4:3", version: "NVI" },
  { month: 3, day: 31, verseText: "Esteja sobre nós a bondade do nosso Deus Soberano. Consolida, para nós, a obra de nossa mãos; consolida a obra de nossas mãos!", verseReference: "Salmos 90:17", version: "NVI" },
  { month: 4, day: 1, verseText: "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti.", verseReference: "Salmos 91:7", version: "ACF" },
  { month: 4, day: 2, verseText: "O Senhor, porém, me disse: \"Não diga que é muito jovem. A todos a quem eu o enviar você irá e dirá tudo o que eu lhe ordenar.", verseReference: "Jeremias 1:7", version: "NVI" },
  { month: 4, day: 3, verseText: "Cresçam, porém, na graça e no conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja a glória, agora e para sempre! Amém.", verseReference: "2 Pedro 3:18", version: "NVI" },
  { month: 4, day: 4, verseText: "Venham, adoremos e prostremo-nos; ajoelhemos diante do Senhor, que nos criou.", verseReference: "Salmos 95:6", version: "NAA" },
  { month: 4, day: 5, verseText: "Cantai ao Senhor, bendizei o seu nome; anunciai a sua salvação de dia em dia.", verseReference: "Salmos 96:2", version: "ACF" },
  { month: 4, day: 6, verseText: "sendo agora revelada pela manifestação de nosso Salvador, Cristo Jesus. Ele tornou inoperante a morte e trouxe à luz a vida e a imortalidade por meio do evangelho.", verseReference: "2 Timóteo 1:10", version: "NVI" },
  { month: 4, day: 7, verseText: "Por isso, vistam toda a armadura de Deus, para que possam resistir no dia mau e permanecer inabaláveis, depois de terem feito tudo.", verseReference: "Efésios 6:13", version: "NVI" },
  { month: 4, day: 8, verseText: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", verseReference: "Salmos 46:1", version: "ACF" },
  { month: 4, day: 9, verseText: "Como um pai se compadece de seus filhos, assim o Senhor se compadece dos que o temem.", verseReference: "Salmos 103:13", version: "NAA" },
  { month: 4, day: 10, verseText: "\"Eis que venho em breve! Feliz é aquele que guarda as palavras da profecia deste livro\".", verseReference: "Apocalipse 22:7", version: "NVI" },
  { month: 4, day: 11, verseText: "Mas entre vocês não pode ser assim. Pelo contrário, quem quiser ser importante, que sirva os outros,", verseReference: "Marcos 10:43", version: "ARC" },
  { month: 4, day: 12, verseText: "Jesus respondeu: \"Está escrito: ‘Nem só de pão viverá o homem, mas de toda palavra que procede da boca de Deus’\".", verseReference: "Mateus 4:4", version: "NVI" },
  { month: 4, day: 13, verseText: "Porque Deus não é injusto para se esquecer da vossa obra e do trabalho de amor que, para com o seu nome, mostrastes, enquanto servistes aos santos e ainda servis.", verseReference: "Hebreus 6:10", version: "ARC" },
  { month: 4, day: 14, verseText: "Desde os tempos antigos ninguém ouviu, nenhum ouvido percebeu, e olho nenhum viu outro Deus, além de ti, que trabalha para aqueles que nele esperam.", verseReference: "Isaías 64:4", version: "NVI" },
  { month: 4, day: 15, verseText: "Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, que não muda como sombras inconstantes.", verseReference: "Tiago 1:17", version: "NVI" },
  { month: 4, day: 16, verseText: "O Senhor é a minha força e o meu escudo; nele confiou o meu coração, и fui socorrido; pelo que o meu coração salta de prazer, e com o meu canto o louvarei.", verseReference: "Salmos 28:7", version: "ACF" },
  { month: 4, day: 17, verseText: "Porque vocês, irmãos, foram chamados para viver em liberdade. Não a usem, porém, para satisfazer sua natureza humana. Ao contrário, usem-na para servir uns aos outros em amor.", verseReference: "Gálatas 5:13", version: "NVT" },
  { month: 4, day: 18, verseText: "Pois nada é impossível para Deus\".", verseReference: "Lucas 1:37", version: "NVI" },
  { month: 4, day: 19, verseText: "Cada um exerça o dom que recebeu para servir os outros, administrando fielmente a graça de Deus em suas múltiplas formas.", verseReference: "1 Pedro 4:10", version: "NVI" },
  { month: 4, day: 20, verseText: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.", verseReference: "Provérbios 16:3", version: "NVI" },
  { month: 4, day: 21, verseText: "O Espírito e a noiva dizem: \"Vem! \" E todo aquele que ouvir diga: \"Vem! \" Quem tiver sede, venha; e quem quiser, beba de graça da água da vida.", verseReference: "Apocalipse 22:17", version: "NVI" },
  { month: 4, day: 22, verseText: "Fui exemplo constante de como podemos, com trabalho árduo, ajudar os necessitados, lembrando as palavras do Senhor Jesus: ‘Há bênção maior em dar que em receber’\".", verseReference: "Atos dos Apóstolos 20:35", version: "NVT" },
  { month: 4, day: 23, verseText: "Sigam as leis do Senhor, nosso Deus; temam a Deus, obedeçam aos seus mandamentos e deem atenção a tudo o que ele diz. Adorem somente a Deus e fiquem ligados com ele.", verseReference: "Deuteronômio 13:4", version: "NTLH" },
  { month: 4, day: 24, verseText: "\"Eu lhes disse essas coisas para que em mim vocês tenham paz. Neste mundo vocês terão aflições; contudo, tenham ânimo! Eu venci o mundo\".", verseReference: "João 16:33", version: "NVI" },
  { month: 4, day: 25, verseText: "É melhor obter sabedoria do que ouro! É melhor obter entendimento do que prata!", verseReference: "Provérbios 16:16", version: "NVI" },
  { month: 4, day: 26, verseText: "Mas guardem fielmente o mandamento e a lei que Moisés, servo do Senhor, deu a vocês, que amem o Senhor, o seu Deus, andem em todos os seus caminhos, obedeçam aos seus mandamentos, apeguem-se a ele e o sirvam de todo o coração e de toda a alma\".", verseReference: "Josué 22:5", version: "NVI" },
  { month: 4, day: 27, verseText: "Nunca falte a vocês o zelo, sejam fervorosos no espírito, sirvam ao Senhor.", verseReference: "Romanos 12:11", version: "NVI" },
  { month: 4, day: 28, verseText: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", verseReference: "2 Timóteo 1:7", version: "NVI" },
  { month: 4, day: 29, verseText: "Quanto a você, porém, permaneça nas coisas que aprendeu e das quais tem convicção, pois você sabe de quem o aprendeu.", verseReference: "2 Timóteo 3:14", version: "NVI" },
  { month: 4, day: 30, verseText: "\"Honra teu pai e tua mãe, a fim de que tenhas vida longa na terra que o Senhor teu Deus te dá.", verseReference: "Êxodo 20:12", version: "NVI" },
  { month: 5, day: 1, verseText: "Vocês não sabem que são santuário de Deus e que o Espírito de Deus habita em vocês?", verseReference: "1 Coríntios 3:16", version: "NVI" },
  { month: 5, day: 2, verseText: "Assim, quer vocês comam, bebam ou façam qualquer outra coisa, façam tudo para a glória de Deus.", verseReference: "1 Coríntios 10:31", version: "NVI" },
  { month: 5, day: 3, verseText: "Honre o Senhor com todos os seus recursos e com os primeiros frutos de todas as suas plantações;", verseReference: "Provérbios 3:9", version: "NVI" },
  { month: 5, day: 4, verseText: "Já fui jovem e agora sou velho, mas nunca vi o justo desamparado, nem seus filhos mendigando o pão.", verseReference: "Salmos 37:25", version: "NVI" },
  { month: 5, day: 5, verseText: "No princípio era a Palavra, e a Palavra estava com Deus e a Palavra era Deus.", verseReference: "João 1:1", version: "NVI" },
  { month: 5, day: 6, verseText: "Se você confessar com a sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dentre os mortos, será salvo.", verseReference: "Romanos 10:9", version: "NVI" },
  { month: 5, day: 7, verseText: "Mas de fato Cristo ressuscitou dentre os mortos, sendo as primícias dentre aqueles que dormiram.", verseReference: "1 Coríntios 15:20", version: "NVI" },
  { month: 5, day: 8, verseText: "Dai ao Senhor a glória devida ao seu nome; trazei oferenda, e entrai nos seus átrios.", verseReference: "Salmos 96:8", version: "ACF" },
  { month: 5, day: 9, verseText: "Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: \"O justo viverá pela fé\".", verseReference: "Romanos 1:17", version: "NVI" },
  { month: 5, day: 10, verseText: "Bendigam o Senhor todas as suas obras, em todos os lugares do seu domínio. Bendiga, minha alma, o Senhor.", verseReference: "Salmos 103:22", version: "NAA" },
  { month: 5, day: 11, verseText: "Ele os chamou para isso por meio de nosso evangelho, a fim de tomarem posse da glória de nosso Senhor Jesus Cristo.", verseReference: "2 Tessalonicenses 2:14", version: "NVI" },
  { month: 5, day: 12, verseText: "Cada um dê conforme determinou em seu coração, não com pesar ou por obrigação, pois Deus ama quem dá com alegria.", verseReference: "2 Coríntios 9:7", version: "NVI" },
  { month: 5, day: 13, verseText: "Combata o bom combate da fé. Tome posse da vida eterna, para a qual você foi chamado e fez a boa confissão na presença de muitas testemunhas.", verseReference: "1 Timóteo 6:12", version: "NVI" },
  { month: 5, day: 14, verseText: "O vento sopra onde quer. Você o escuta, mas não pode dizer de onde vem nem para onde vai. Assim acontece com todos os nascidos do Espírito\".", verseReference: "João 3:8", version: "NVI" },
  { month: 5, day: 15, verseText: "Estejam vigilantes, mantenham-se firmes na fé, sejam homens de coragem, sejam fortes.", verseReference: "1 Coríntios 16:13", version: "NVI" },
  { month: 5, day: 16, verseText: "Se o seu dom é servir, sirva; se é ensinar, ensine;", verseReference: "Romanos 12:7", version: "NVI" },
  { month: 5, day: 17, verseText: "\"Estejam prontos para servir e conservem acesas as suas candeias,", verseReference: "Romanos Lucas 12:35", version: "NVI" },
  { month: 5, day: 18, verseText: "Acaso busco eu agora a aprovação dos homens ou a de Deus? Ou estou tentando agradar a homens? Se eu ainda estivesse procurando agradar a homens, não seria servo de Cristo.", verseReference: "Gálatas 1:10", version: "NVI" },
  { month: 5, day: 19, verseText: "Ame o Senhor, o seu Deus de todo o seu coração, de toda a sua alma, de todo o seu entendimento e de todas as suas forças’.", verseReference: "Mateus 12:30", version: "NVI" },
  { month: 5, day: 20, verseText: "\"Então purificarei os lábios dos povos, para que todos eles invoquem o nome do Senhor e o sirvam de comum acordo.", verseReference: "Sofonias 3:9", version: "NVI" },
  { month: 5, day: 21, verseText: "Por isso, exortem-se e edifiquem-se uns aos outros, como de fato vocês estão fazendo.", verseReference: "1 Tessalonicenses 5:11", version: "NVI" },
  { month: 5, day: 22, verseText: "Pela fé entendemos que o universo foi formado pela palavra de Deus, de modo que o que se vê não foi feito do que é visível.", verseReference: "Hebreus 11:3", version: "NVI" },
  { month: 5, day: 23, verseText: "E eu lhe digo que você é Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do Hades não poderão vencê-la.", verseReference: "Mateus 16:18", version: "NVI" },
  { month: 5, day: 24, verseText: "Pois o Senhor é quem dá sabedoria; de sua boca procedem o conhecimento e o discernimento.", verseReference: "Provérbios 2:6", version: "NVI" },
  { month: 5, day: 25, verseText: "Já não os chamo servos, porque o servo não sabe o que o seu senhor faz. Em vez disso, eu os tenho chamado amigos, porque tudo o que ouvi de meu Pai eu lhes tornei conhecido.", verseReference: "João 15:15", version: "NVI" },
  { month: 5, day: 26, verseText: "Livrem-se do fermento velho, para que sejam massa nova e sem fermento, como realmente são. Pois Cristo, nosso Cordeiro pascal, foi sacrificado.", verseReference: "1 Coríntios 5:7", version: "NVI" },
  { month: 5, day: 27, verseText: "E conhecereis a verdade, e a verdade vos libertará.", verseReference: "João 8:32", version: "ACF" },
  { month: 5, day: 28, verseText: "Pois Deus enviou o seu Filho ao mundo, não para condenar o mundo, mas para que este fosse salvo por meio dele.", verseReference: "João 3:17", version: "NVI" },
  { month: 5, day: 29, verseText: "Tenham-nos na mais alta estima, com amor, por causa do trabalho deles. Vivam em paz uns com os outros.", verseReference: "1 Tessalonicenses 5:13", version: "NVI" },
  { month: 5, day: 30, verseText: "Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo,", verseReference: "Efésios 4:15", version: "ARC" },
  { month: 5, day: 31, verseText: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore, nem se desanime, pois o Senhor, o seu Deus, estará com você por onde você andar\".", verseReference: "Josué 1:9", version: "NVI" },
  { month: 6, day: 1, verseText: "O Espírito do Soberano Senhor está sobre mim porque o Senhor ungiu-me para levar boas notícias aos pobres. Enviou-me para cuidar dos que estão com o coração quebrantado, anunciar liberdade aos cativos e libertação das trevas aos prisioneiros,", verseReference: "Isaías 61:1", version: "NVI" },
  { month: 6, day: 2, verseText: "Deus nos ressuscitou com Cristo e com ele nos fez assentar nos lugares celestiais em Cristo Jesus,", verseReference: "Efésios 2:6", version: "NVI" },
  { month: 6, day: 3, verseText: "Adorai ao Senhor na beleza da santidade; tremei diante dele toda a terra.", verseReference: "Salmos 96:9", version: "ACF" },
  { month: 6, day: 4, verseText: "Felizes os servos cujo senhor os encontrar vigiando, quando voltar. Eu afirmo que ele se vestirá para servir, fará que se reclinem à mesa, e virá servi-los.", verseReference: "Romanos Lucas 12:37", version: "NVI" },
  { month: 6, day: 5, verseText: "\"Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna.", verseReference: "João 3:16", version: "NVI" },
  { month: 6, day: 6, verseText: "Assim, fixamos os olhos, não naquilo que se vê, mas no que não se vê, pois o que se vê é transitório, mas o que não se vê é eterno.", verseReference: "2 Coríntios 4:18", version: "NVI" },
  { month: 6, day: 7, verseText: "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.", verseReference: "2 Coríntios 5:17", version: "ACF" },
  { month: 6, day: 8, verseText: "Alegrei-me quando me disseram: Vamos à Casa do Senhor!", verseReference: "Salmos 122:1", version: "ARC" },
  { month: 6, day: 9, verseText: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou com todas as bênçãos espirituais nas regiões celestiais em Cristo.", verseReference: "Efésios 1:3", version: "NVI" },
  { month: 6, day: 10, verseText: "Seja a amabilidade de vocês conhecida por todos. Perto está o Senhor.", verseReference: "Filipenses 4:5", version: "NVI" },
  { month: 6, day: 11, verseText: "Dele todo o corpo, ajustado e unido pelo auxílio de todas as juntas, cresce e edifica-se a si mesmo em amor, na medida em que cada parte realiza a sua função.", verseReference: "Efésios 4:16", version: "NVI" },
  { month: 6, day: 12, verseText: "Todos os dias, unidos, se reuniam no pátio do Templo. E nas suas casas partiam o pão e participavam das refeições com alegria e humildade.", verseReference: "Atos dos Apóstolos 2:46", version: "NTLH" },
  { month: 6, day: 13, verseText: "Mantenham-se no amor de Deus, enquanto esperam que a misericórdia de nosso Senhor Jesus Cristo os leve para a vida eterna.", verseReference: "Judas 1:21", version: "NVI" },
  { month: 6, day: 14, verseText: "O Senhor é bom para com aqueles cuja esperança está nele, para com aqueles que o buscam.", verseReference: "Lamentações de Jeremias 3:25", version: "NVI" },
  { month: 6, day: 15, verseText: "assim também em Cristo nós, que somos muitos, formamos um corpo, e cada membro está ligado a todos os outros.", verseReference: "Romanos 12:5", version: "NVI" },
  { month: 6, day: 16, verseText: "Portanto, que diremos, irmãos? Quando vocês se reúnem, cada um de vocês tem um salmo, ou uma palavra de instrução, uma revelação, uma palavra em uma língua ou uma interpretação. Tudo seja feito para a edificação da igreja.", verseReference: "1 Coríntios 14:26", version: "NVI" },
  { month: 6, day: 17, verseText: "falando entre vocês com salmos, hinos e cânticos espirituais, cantando e louvando de coração ao Senhor,", verseReference: "Efésios 5:19", version: "NVI" },
  { month: 6, day: 18, verseText: "Mesmo quando eu andar por um vale de trevas e morte, não temerei perigo algum, pois tu estás comigo; a tua vara e o teu cajado me protegem.", verseReference: "Salmos 23:4", version: "NVI" },
  { month: 6, day: 19, verseText: "Bem-aventurados os puros de coração, pois verão a Deus.", verseReference: "Mateus 5:8", version: "NVI" },
  { month: 6, day: 20, verseText: "O meu mandamento é este: amem-se uns aos outros como eu os amei.", verseReference: "João 15:12", version: "NVI" },
  { month: 6, day: 21, verseText: "Edifiquem-se, porém, amados, na santíssima fé que vocês têm, orando no Espírito Santo.", verseReference: "Judas 1:20", version: "NVI" },
  { month: 6, day: 22, verseText: "Vocês, porém, são geração eleita, sacerdócio real, nação santa, povo exclusivo de Deus, para anunciar as grandezas daquele que os chamou das trevas para a sua maravilhosa luz.", verseReference: "1 Pedro 2:9", version: "NVI" },
  { month: 6, day: 23, verseText: "E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.", verseReference: "2 Coríntios 12:9", version: "ARC" },
  { month: 6, day: 24, verseText: "Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas, diante de Deus, as vossas petições, pela oração e pela súplica, com ações de graças.", verseReference: "Filipenses 4:6", version: "ARA" },
  { month: 6, day: 25, verseText: "Pôs um novo cântico na minha boca, um hino de louvor ao nosso Deus. Muitos verão isso e temerão, e confiarão no Senhor.", verseReference: "Salmos 40:3", version: "NVI" },
  { month: 6, day: 26, verseText: "Pois assim diz o Alto e Sublime, que vive para sempre, e cujo nome é santo: \"Habito num lugar alto e santo, mas habito também com o contrito e humilde de espírito, para dar novo ânimo ao espírito do humilde e novo alento ao coração do contrito.", verseReference: "Isaías 57:15", version: "NVI" },
  { month: 6, day: 27, verseText: "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?", verseReference: "Romanos 8:31", version: "NVI" },
  { month: 6, day: 28, verseText: "Cantem de alegria ao Senhor, vocês que são justos; aos que são retos fica bem louvá-lo.", verseReference: "Salmos 33:1", version: "NVI" },
  { month: 6, day: 29, verseText: "ensinando-os a obedecer a tudo o que eu lhes ordenei. E eu estarei sempre com vocês, até o fim dos tempos\".", verseReference: "Mateus 28:20", version: "NVI" },
  { month: 6, day: 30, verseText: "Então a profetisa Miriã, irmã de Arão, pegou um tamborim e todas as mulheres a seguiram, tocando tamborins e dançando.", verseReference: "Êxodo 15:20", version: "ARC" },
  { month: 7, day: 1, verseText: "Temos diferentes dons, de acordo com a graça que nos foi dada. Se alguém tem o dom de profetizar, use-o na proporção da sua fé.", verseReference: "Romanos 12:6", version: "NVI" },
  { month: 7, day: 2, verseText: "Se é santa a parte da massa que é oferecida como primeiros frutos, toda a massa também o é; se a raiz é santa, os ramos também o serão.", verseReference: "Romanos 11:16", version: "NVI" },
  { month: 7, day: 3, verseText: "\"Mas bendito é o homem cuja confiança está no Senhor, cuja confiança nele está.", verseReference: "Jeremias 17:7", version: "NVI" },
  { month: 7, day: 4, verseText: "Ora, vocês são o corpo de Cristo, e cada um de vocês, individualmente, é membro desse corpo.", verseReference: "1 Coríntios 12:27", version: "NVI" },
  { month: 7, day: 5, verseText: "Louvavam a Deus por tudo e eram estimados por todos. E cada dia o Senhor juntava ao grupo as pessoas que iam sendo salvas.", verseReference: "Atos dos Apóstolos 2:47", version: "NTLH" },
  { month: 7, day: 6, verseText: "Nisto conhecemos o que é o amor: Jesus Cristo deu a sua vida por nós, e devemos dar a nossa vida por nossos irmãos.", verseReference: "1 João 3:16", version: "NVI" },
  { month: 7, day: 7, verseText: "Louvem o Senhor com harpa; ofereçam-lhe música com lira de dez cordas.", verseReference: "Salmos 33:2", version: "NVI" },
  { month: 7, day: 8, verseText: "Mas, vocês devem ser fortes e não se desanimar, pois o trabalho de vocês será recompensado\".", verseReference: "2 Coríntios 15:7", version: "NVI" },
  { month: 7, day: 9, verseText: "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça,", verseReference: "2 Timóteo 3:16", version: "NVI" },
  { month: 7, day: 10, verseText: "\"Ouçam, ó reis! Governantes, escutem! Cantarei ao Senhor, cantarei; comporei músicas ao Senhor, o Deus de Israel.", verseReference: "Juízes 5:3", version: "NVI" },
  { month: 7, day: 11, verseText: "E, porque vocês são filhos, Deus enviou o Espírito de seu Filho aos seus corações, o qual clama: \"Aba, Pai\".", verseReference: "Gálatas 4:6", version: "NVI" },
  { month: 7, day: 12, verseText: "Jesus lhes deu esta resposta: \"Eu lhes digo verdadeiramente que o Filho não pode fazer nada de si mesmo; só pode fazer o que vê o Pai fazer, porque o que o Pai faz o Filho também faz.", verseReference: "João 5:19", version: "NVI" },
  { month: 7, day: 13, verseText: "Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo,", verseReference: "Mateus 28:19", version: "NVI" },
  { month: 7, day: 14, verseText: "Davi e todos os israelitas iam cantando e dançando perante o Senhor, ao som de todo tipo de instrumentos de pinho: harpas, liras, tamborins, chocalhos e címbalos.", verseReference: "2 Samuel 6:5", version: "NVI" },
  { month: 7, day: 15, verseText: "Sempre que o espírito mandado por Deus se apoderava de Saul, Davi apanhava sua harpa e tocava. Então Saul sentia alívio e melhorava, e o espírito maligno o deixava.", verseReference: "1 Samuel 16:23", version: "NVI" },
  { month: 7, day: 16, verseText: "Cantem louvores a Deus, cantem louvores, cantem louvores ao nosso Rei, cantem louvores!", verseReference: "Salmos 47:6", version: "NVT" },
  { month: 7, day: 17, verseText: "Que a paz de Cristo seja o juiz em seus corações, visto que vocês foram chamados a viver em paz, como membros de um só corpo. E sejam agradecidos.", verseReference: "Colossenses 3:15", version: "NVI" },
  { month: 7, day: 18, verseText: "Davi também ordenou aos líderes dos levitas que encarregassem os músicos que havia entre eles de cantar músicas alegres, acompanhados por instrumentos musicais: liras, harpas e címbalos sonoros.", verseReference: "1 Crônicas 15:16", version: "NVI" },
  { month: 7, day: 19, verseText: "Os que tocavam trombetas e os cantores, em uníssono, louvaram e agradeceram ao Senhor. Acompanhados de trombetas, címbalos e outros instrumentos, levantaram as vozes e louvaram o Senhor com estas palavras: \"Ele é bom! Seu amor dura para sempre!\". Nesse momento, uma densa nuvem encheu o templo do Senhor.", verseReference: "2 Crônicas 5:13", version: "NVI" },
  { month: 7, day: 20, verseText: "O amigo ama em todos os momentos; é um irmão na adversidade.", verseReference: "Provérbios 17:17", version: "NVI" },
  { month: 7, day: 21, verseText: "\"Cada palavra de Deus é comprovadamente pura. Ele é um escudo para quem nele se refugia.", verseReference: "Provérbios 30:5", version: "NVI" },
  { month: 7, day: 22, verseText: "Mas, assim como é santo aquele que os chamou, sejam santos vocês também em tudo o que fizerem,", verseReference: "1 Pedro 1:15", version: "NVI" },
  { month: 7, day: 23, verseText: "Ao recebê-lo, os quatro seres viventes e os vinte e quatro anciãos prostraram-se diante do Cordeiro. Cada um deles tinha uma harpa e taças de ouro cheias de incenso, que são as orações dos santos;", verseReference: "Apocalipse 5:8", version: "NVI" },
  { month: 7, day: 24, verseText: "Orem continuamente.", verseReference: "1 Tessalonicenses 5:17", version: "NVI" },
  { month: 7, day: 25, verseText: "Quanto a mim, que eu jamais me glorie, a não ser na cruz de nosso Senhor Jesus Cristo, por meio da qual o mundo foi crucificado para mim, e eu para o mundo.", verseReference: "Gálatas 6:14", version: "NVI" },
  { month: 7, day: 26, verseText: "Cantem para ele e louvem-no; relatem todas as suas maravilhas.", verseReference: "Salmos 105:2", version: "NVI" },
  { month: 7, day: 27, verseText: "Acima de tudo, guarde o seu coração, pois dele depende toda a sua vida.", verseReference: "Provérbios 4:23", version: "NVI" },
  { month: 7, day: 28, verseText: "Ninguém o despreze pelo fato de você ser jovem, mas seja um exemplo para os fiéis na palavra, no procedimento, no amor, na fé e na pureza.", verseReference: "1 Timóteo 4:12", version: "NVI" },
  { month: 7, day: 29, verseText: "Cantarei ao Senhor toda a minha vida; louvarei ao meu Deus enquanto eu viver.", verseReference: "Salmos 104:33", version: "NVI" },
  { month: 7, day: 30, verseText: "Simão Pedro lhe respondeu: \"Senhor, para quem iremos? Tu tens as palavras de vida eterna.", verseReference: "João 6:68", version: "NVI" },
  { month: 7, day: 31, verseText: "Pois todas as nações andam, cada uma em nome dos seus deuses, mas nós andaremos no nome do Senhor, o nosso Deus, para todo o sempre.", verseReference: "Miquéias 4:5", version: "NVI" },
  { month: 8, day: 1, verseText: "‘Clame a mim e eu responderei e lhe direi coisas grandiosas e insondáveis que você não conhece’.", verseReference: "Jeremias 33:3", version: "NVI" },
  { month: 8, day: 2, verseText: "Que a minha oração chegue diante de ti; inclina os teus ouvidos ao meu clamor.", verseReference: "Salmos 88:2", version: "NVI" },
  { month: 8, day: 3, verseText: "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele, para que vocês transbordem de esperança, pelo poder do Espírito Santo.", verseReference: "Romanos 15:13", version: "NVI" },
  { month: 8, day: 4, verseText: "Vocês estudam cuidadosamente as Escrituras, porque pensam que nelas vocês têm a vida eterna. E são as Escrituras que testemunham a meu respeito;", verseReference: "João 5:39", version: "NVI" },
  { month: 8, day: 5, verseText: "Sem fé é impossível agradar a Deus, pois quem dele se aproxima precisa crer que ele existe e que recompensa aqueles que o buscam.", verseReference: "Hebreus 11:6", version: "NVI" },
  { month: 8, day: 6, verseText: "Cantem-lhe uma nova canção; toquem com habilidade ao aclamá-lo.", verseReference: "Salmos 33:3", version: "NVI" },
  { month: 8, day: 7, verseText: "Pois Deus é o Rei de toda a terra; louvem-no com um salmo.", verseReference: "Salmos 47:7", version: "NVT" },
  { month: 8, day: 8, verseText: "Contudo, alegrem-se, não porque os espíritos se submetem a vocês, mas porque seus nomes estão escritos nos céus\".", verseReference: "Lucas 10:20", version: "NVI" },
  { month: 8, day: 9, verseText: "Feliz é o homem que persevera na provação, porque depois de aprovado receberá a coroa da vida que Deus prometeu aos que o amam.", verseReference: "Tiago 1:12", version: "NVI" },
  { month: 8, day: 10, verseText: "Vejam como é grande o amor que o Pai nos concedeu: que fôssemos chamados filhos de Deus, o que de fato somos! Por isso o mundo não nos conhece, porque não o conheceu.", verseReference: "1 João 3:1", version: "NVI" },
  { month: 8, day: 11, verseText: "Ele o fez a fim de que, justificados por sua graça, nos tornemos seus herdeiros, tendo a esperança da vida eterna.", verseReference: "Tito 3:7", version: "NVI" },
  { month: 8, day: 12, verseText: "Quenanias, o chefe dos levitas, ficou encarregado dos cânticos; essa era sua responsabilidade, pois ele tinha competência para isso.", verseReference: "1 Crônicas 15:22", version: "NVI" },
  { month: 8, day: 13, verseText: "como o Filho do homem, que não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos\".", verseReference: "Mateus 20:28", version: "NVI" },
  { month: 8, day: 14, verseText: "Ele corta todo ramo que, estando em mim, não der fruto. E poda todo aquele que der fruto, para que dê mais fruto ainda.", verseReference: "João 15:2", version: "NVI" },
  { month: 8, day: 15, verseText: "Quem me serve precisa seguir-me; e, onde estou, o meu servo também estará. Aquele que me serve, meu Pai o honrará.", verseReference: "João 12:26", version: "NVI" },
  { month: 8, day: 16, verseText: "Portanto, irmãos, peço, pelas misericórdias de Deus, que ofereçam o corpo de vocês como sacrifício vivo, santo e agradável a Deus: este é o culto racional de vocês.", verseReference: "Romanos 12:1", version: "NVI" },
  { month: 8, day: 17, verseText: "Estou crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo‑a pela fé no Filho de Deus, que me amou e se entregou por mim.", verseReference: "Gálatas 2:20", version: "NVI" },
  { month: 8, day: 18, verseText: "E esta é a vontade daquele que me enviou: que eu não perca nenhum dos que ele me deu, mas os ressuscite no último dia.", verseReference: "João 6:39", version: "NVI" },
  { month: 8, day: 19, verseText: "Nós, porém, não recebemos o espírito do mundo, mas o Espírito procedente de Deus, para que entendamos as coisas que Deus nos tem dado gratuitamente.", verseReference: "1 Coríntios 2:12", version: "NVI" },
  { month: 8, day: 20, verseText: "Mas acumulem para vocês tesouros nos céus, onde a traça e a ferrugem não destroem e onde os ladrões não arrombam nem furtam.", verseReference: "Mateus 6:20", version: "NVI" },
  { month: 8, day: 21, verseText: "Eu lhes darei um coração novo e porei um espírito novo no interior de vocês. Tirarei de vocês o coração de pedra e, em troca, darei um coração de carne.", verseReference: "Ezequiel 36:26", version: "NVI" },
  { month: 8, day: 22, verseText: "Todavia, não me importo, nem considero a minha vida de valor algum para mim mesmo, se tão-somente puder terminar a corrida e completar o ministério que o Senhor Jesus me confiou, de testemunhar do evangelho da graça de Deus.", verseReference: "Atos dos Apóstolos 20:24", version: "NVI" },
  { month: 8, day: 23, verseText: "Disse-lhe Jesus: Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim.", verseReference: "João 14:6", version: "ACF" },
  { month: 8, day: 24, verseText: "Pois onde se reunirem dois ou três em meu nome, ali eu estou no meio deles\".", verseReference: "Mateus 18:20", version: "NVI" },
  { month: 8, day: 25, verseText: "Quem é sábio e tem entendimento entre vocês? Que o demonstre por seu bom procedimento, mediante obras praticadas com a humildade que provém da sabedoria.", verseReference: "Tiago 3:13", version: "NVI" },
  { month: 8, day: 26, verseText: "Procure obter sabedoria e entendimento; não se esqueça das minhas palavras nem delas se afaste.", verseReference: "Provérbios 4:5", version: "NVI" },
  { month: 8, day: 27, verseText: "Nós amamos porque ele nos amou primeiro.", verseReference: "1 João 4:19", version: "NVI" },
  { month: 8, day: 28, verseText: "É por meio de Cristo que todos nós, judeus e não judeus, podemos ir, pelo poder de um só Espírito, até a presença do Pai.", verseReference: "Efésios 2:18", version: "NTLH" },
  { month: 8, day: 29, verseText: "Não sobreveio a vocês tentação que não fosse comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele lhes providenciará um escape, para que o possam suportar.", verseReference: "1 Coríntios 10:13", version: "NVI" },
  { month: 8, day: 30, verseText: "Pois eu sou o Senhor, o seu Deus, que o segura pela mão direita e lhe diz: Não tema; eu o ajudarei.", verseReference: "Isaías 41:13", version: "NVI" },
  { month: 8, day: 31, verseText: "E vimos e testemunhamos que o Pai enviou seu Filho para ser o Salvador do mundo.", verseReference: "1 João 4:14", version: "NVI" },
  { month: 9, day: 1, verseText: "e eles cantavam um cântico novo: \"Tu és digno de receber o livro e de abrir os seus selos, pois foste morto e com teu sangue compraste para Deus gente de toda tribo, língua, povo e nação.", verseReference: "Apocalipse 5:9", version: "NVI" },
  { month: 9, day: 2, verseText: "\"Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.", verseReference: "Mateus 11:28", version: "NVI" },
  { month: 9, day: 3, verseText: "E Jesus disse-lhe: Se tu podes crer, tudo é possível ao que crê.", verseReference: "Marcos 9:23", version: "ACF" },
  { month: 9, day: 4, verseText: "Não abandone a sabedoria, e ela o protegerá; ame-a, e ela cuidará de você.", verseReference: "Provérbios 4:6", version: "NVI" },
  { month: 9, day: 5, verseText: "Tudo posso naquele que me fortalece.", verseReference: "Filipenses 4:13", version: "NVI" },
  { month: 9, day: 6, verseText: "\"Eis que venho em breve! A minha recompensa está comigo, e eu retribuirei a cada um de acordo com o que fez.", verseReference: "Apocalipse 22:12", version: "NVI" },
  { month: 9, day: 7, verseText: "se o meu povo, que se chama pelo meu nome, se humilhar e orar, buscar a minha face e se afastar dos seus maus caminhos, dos céus o ouvirei, perdoarei o seu pecado e curarei a sua terra.", verseReference: "2 Crônicas 7:14", version: "NVI" },
  { month: 9, day: 8, verseText: "Não há judeu nem grego, escravo nem livre, homem nem mulher; pois todos são um em Cristo Jesus.", verseReference: "Gálatas 3:28", version: "NVI" },
  { month: 9, day: 9, verseText: "Agora que já se ouviu tudo, aqui está a conclusão: Tema a Deus e guarde os seus mandamentos, pois isso é o essencial para o homem.", verseReference: "Eclesiastes 12:13", version: "NVI" },
  { month: 9, day: 10, verseText: "Observem os corvos: não semeiam nem colhem, não têm armazéns nem celeiros; contudo, Deus os alimenta. E vocês têm muito mais valor do que as aves!", verseReference: "Lucas 12:24", version: "NVI" },
  { month: 9, day: 11, verseText: "A lei foi introduzida para que a transgressão fosse ressaltada. Mas onde aumentou o pecado, transbordou a graça,", verseReference: "Romanos 5:20", version: "NVI" },
  { month: 9, day: 12, verseText: "Gravem estas minhas palavras no coração e na mente; amarrem‑nas como sinal nas mãos e prendam‑nas na testa.", verseReference: "Deuteronômio 11:18", version: "NVI" },
  { month: 9, day: 13, verseText: "E o meu Deus, segundo a sua riqueza em glória, há de suprir, em Cristo Jesus, cada uma de vossas necessidades.", verseReference: "Filipenses 4:19", version: "ARA" },
  { month: 9, day: 14, verseText: "Desde o nascer até o pôr do sol, que o nome do SENHOR seja louvado!", verseReference: "Salmos 113:3", version: "ARA" },
  { month: 9, day: 15, verseText: "Como, então, invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram? E como ouvirão se não houver quem pregue?", verseReference: "Romanos 10:14", version: "NVI" },
  { month: 9, day: 16, verseText: "deu-nos vida juntamente com Cristo, quando ainda estávamos mortos em transgressões — pela graça vocês são salvos.", verseReference: "Efésios 2:5", version: "NVI" },
  { month: 9, day: 17, verseText: "Como são felizes os que obedecem aos seus estatutos e de todo o coração o buscam!", verseReference: "Salmos 119:2", version: "NVI" },
  { month: 9, day: 18, verseText: "Portanto, já que vocês ressuscitaram com Cristo, dediquem‑se às coisas que são do alto, onde Cristo está, assentado à direita de Deus.", verseReference: "Colossenses 3:1", version: "NVI" },
  { month: 9, day: 19, verseText: "Então, Moisés lhe declarou: ― Se não fores conosco, não nos faças sair daqui.", verseReference: "Êxodo 33:15", version: "NVI" },
  { month: 9, day: 20, verseText: "E tudo o que pedirem em oração, se crerem, vocês receberão\".", verseReference: "Mateus 21:22", version: "NVI" },
  { month: 9, day: 21, verseText: "Entre vocês há alguém que está sofrendo? Que ele ore. Há alguém que se sente feliz? Que ele cante louvores.", verseReference: "Tiago 5:13", version: "NVI" },
  { month: 9, day: 22, verseText: "Todavia, como está escrito: \"Olho nenhum viu, ouvido nenhum ouviu, mente nenhuma imaginou o que Deus preparou para aqueles que o amam\";", verseReference: "1 Coríntios 2:9", version: "NVI" },
  { month: 9, day: 23, verseText: "Entrai pelas portas dele com gratidão, e em seus átrios com louvor; louvai-o, e bendizei o seu nome.", verseReference: "Salmos 100:4", version: "ACF" },
  { month: 9, day: 24, verseText: "Se somos filhos, então somos herdeiros; herdeiros de Deus e co-herdeiros com Cristo, se de fato participamos dos seus sofrimentos, para que também participemos da sua glória.", verseReference: "Romanos 8:17", version: "NVI" },
  { month: 9, day: 25, verseText: "Quem nele crê não é condenado, mas quem não crê já está condenado, por não crer no nome do Filho Unigênito de Deus.", verseReference: "João 3:18", version: "NVI" },
  { month: 9, day: 26, verseText: "Destruímos argumentos e toda pretensão que se levanta contra o conhecimento de Deus, e levamos cativo todo pensamento, para torná-lo obediente a Cristo.", verseReference: "2 Coríntios 10:5", version: "NVI" },
  { month: 9, day: 27, verseText: "Portanto, confessem os seus pecados uns aos outros e orem uns pelos outros para serem curados. A oração de um justo é poderosa e eficaz.", verseReference: "Tiago 5:16", version: "NVI" },
  { month: 9, day: 28, verseText: "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho.", verseReference: "Salmos 119:105", version: "NVI" },
  { month: 9, day: 29, verseText: "Mais do que isso, considero tudo como perda, comparado com a suprema grandeza do conhecimento de Cristo Jesus, meu Senhor, por cuja causa perdi todas as coisas. Eu as considero como esterco para poder ganhar a Cristo", verseReference: "Filipenses 3:8", version: "NVI" },
  { month: 9, day: 30, verseText: "Porque está escrito: \" ‘Por mim mesmo jurei’, diz o Senhor, ‘diante de mim todo joelho se dobrará e toda língua confessará que sou Deus’ \".", verseReference: "Romanos 14:11", version: "NVI" },
  { month: 10, day: 1, verseText: "A relva murcha, e as flores caem, mas a palavra de nosso Deus permanece para sempre. \"", verseReference: "Isaías 40:8", version: "NVI" },
  { month: 10, day: 2, verseText: "pois está escrito: \"Sejam santos, porque eu sou santo\".", verseReference: "1 Pedro 1:16", version: "NVI" },
  { month: 10, day: 3, verseText: "Não se turbe o vosso coração; credes em Deus, crede também em mim.", verseReference: "João 14:1", version: "NVI" },
  { month: 10, day: 4, verseText: "Então Jesus declarou: \"Eu sou o pão da vida. Aquele que vem a mim nunca terá fome; aquele que crê em mim nunca terá sede.", verseReference: "João 6:35", version: "NVI" },
  { month: 10, day: 5, verseText: "Façam isso, compreendendo o tempo em que vivemos. Chegou a hora de vocês despertarem do sono, porque agora a nossa salvação está mais próxima do que quando cremos.", verseReference: "Romanos 13:11", version: "NVI" },
  { month: 10, day: 6, verseText: "Todos nós, tal qual ovelhas, nos desviamos, cada um de nós se voltou para o seu próprio caminho; e o Senhor fez cair sobre ele a iniqüidade de todos nós.", verseReference: "Isaías 53:6", version: "NVI" },
  { month: 10, day: 7, verseText: "Em seu coração o homem planeja o seu caminho, mas o Senhor determina os seus passos.", verseReference: "Provérbios 16:9", version: "NVI" },
  { month: 10, day: 8, verseText: "Obedeça ao que o Senhor, o seu Deus, exige: Ande nos seus caminhos e obedeça aos seus decretos, aos seus mandamentos, às suas ordenanças e aos seus testemunhos, conforme se acham escritos na Lei de Moisés; assim você prosperará em tudo o que fizer e por onde quer que for,", verseReference: "1 Reis 2:3", version: "NVI" },
  { month: 10, day: 9, verseText: "Os que confiam no Senhor são como o monte Sião, que não se pode abalar, mas permanece para sempre.", verseReference: "Salmos 125:1", version: "NVI" },
  { month: 10, day: 10, verseText: "Quem os condenará? Foi Cristo Jesus que morreu; e mais, que ressuscitou e está à direita de Deus, e também intercede por nós.", verseReference: "Romanos 8:34", version: "NVI" },
  { month: 10, day: 11, verseText: "Pois, onde estiver o seu tesouro, ali também estará o seu coração.", verseReference: "Mateus 6:21", version: "NVI" },
  { month: 10, day: 12, verseText: "Então disse Jesus: \"Deixem vir a mim as crianças e não as impeçam; pois o Reino dos céus pertence aos que são semelhantes a elas\".", verseReference: "Mateus 19:14", version: "NVI" },
  { month: 10, day: 13, verseText: "pois todo aquele que entra no descanso de Deus, também descansa das suas obras, como Deus descansou das suas.", verseReference: "Hebreus 4:10", version: "NVI" },
  { month: 10, day: 14, verseText: "― Um novo mandamento dou a vocês: Amem uns aos outros. Como eu os amei, vocês devem amar uns aos outros.", verseReference: "João 13:34", version: "NVI" },
  { month: 10, day: 15, verseText: "O próprio Senhor irá à sua frente e estará com você; ele nunca o deixará nem o abandonará. Não tenha medo! Não desanime!", verseReference: "Deuteronômio 31:8", version: "NVI" },
  { month: 10, day: 16, verseText: "Estejam também preparados, pois não sabem a hora quando o Filho do homem virá.", verseReference: "Lucas 12:40", version: "NVI" },
  { month: 10, day: 17, verseText: "Pois a palavra de Deus é viva e eficaz, e mais afiada que qualquer espada de dois gumes; ela penetra ao ponto de dividir alma e espírito, juntas e medulas, e julga os pensamentos e intenções do coração.", verseReference: "Hebreus 4:12", version: "NVI" },
  { month: 10, day: 18, verseText: "Então ele chamou a multidão e os discípulos e disse: \"Se alguém quiser acompanhar-me, negue-se a si mesmo, tome a sua cruz e siga-me.", verseReference: "Mateus 8:34", version: "NVI" },
  { month: 10, day: 19, verseText: "Falando novamente ao povo, Jesus disse: \"Eu sou a luz do mundo. Quem me segue, nunca andará em trevas, mas terá a luz da vida\".", verseReference: "João 8:12", version: "NVI" },
  { month: 10, day: 20, verseText: "Quem me serve precisa seguir-me; e, onde estou, o meu servo também estará. Aquele que me serve, meu Pai o honrará.", verseReference: "João 12:26", version: "NVI" },
  { month: 10, day: 21, verseText: "Não nos cansemos de fazer o bem, pois no tempo próprio colheremos se não desistirmos.", verseReference: "Gálatas 6:9", version: "NVI" },
  { month: 10, day: 22, verseText: "O Senhor não demora em cumprir a sua promessa, como alguns julgam. Ao contrário, ele é paciente com vocês e não quer que ninguém pereça, mas que todos cheguem ao arrependimento.", verseReference: "2 Pedro 3:9", version: "NVI" },
  { month: 10, day: 23, verseText: "Portanto, pensem nisto: quem sabe que deve fazer o bem e não o faz comete pecado.", verseReference: "Tiago 4:17", version: "NVI" },
  { month: 10, day: 24, verseText: "Entregue as suas preocupações ao Senhor , e ele o susterá; jamais permitirá que o justo venha a cair.", verseReference: "Salmos 55:22", version: "NVI" },
  { month: 10, day: 25, verseText: "Saibam, portanto, que o Senhor , o seu Deus, é Deus; ele é o Deus fiel, que mantém a aliança e a bondade por mil gerações daqueles que o amam e obedecem aos seus mandamentos.", verseReference: "Deuteronômio 7:9", version: "NVI" },
  { month: 10, day: 26, verseText: "Se o machado está cego e sua lâmina não foi afiada, é preciso golpear com mais força; agir com sabedoria assegura o sucesso.", verseReference: "Eclesiastes 10:10", version: "NVI" },
  { month: 10, day: 27, verseText: "Com amor e fidelidade se faz expiação pelo pecado; com o temor do Senhor o homem evita o mal.", verseReference: "Provérbios 16:6", version: "NVI" },
  { month: 10, day: 28, verseText: "Suportem uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor os perdoou.", verseReference: "Colossenses 3:13", version: "NVI" },
  { month: 10, day: 29, verseText: "Pois o meu jugo é suave e o meu fardo é leve\".", verseReference: "Mateus 11:30", version: "NVI" },
  { month: 10, day: 30, verseText: "Se me vês com agrado, revela-me os teus propósitos, para que eu te conheça e continue sendo aceito por ti. Lembra-te de que esta nação é o teu povo\".", verseReference: "Êxodo 33:13", version: "NVI" },
  { month: 10, day: 31, verseText: "Esforcem-se para ter uma vida tranqüila, cuidar dos seus próprios negócios e trabalhar com as próprias mãos, como nós os instruímos;", verseReference: "1 Tessalonicenses 4:11", version: "NVI" },
  { month: 11, day: 1, verseText: "\"Não há ninguém santo como o Senhor ; não há outro além de ti; não há Rocha como o nosso Deus.", verseReference: "1 Samuel 2:2", version: "NVI" },
  { month: 11, day: 2, verseText: "Àquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós,", verseReference: "Efésios 3:20", version: "NVI" },
  { month: 11, day: 3, verseText: "Pois todo o que pede, recebe; o que busca, encontra; e àquele que bate, a porta será aberta.", verseReference: "Mateus 7:8", version: "NVI" },
  { month: 11, day: 4, verseText: "pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos ou soberanias, poderes ou autoridades; todas as coisas foram criadas por ele e para ele.", verseReference: "Colossenses 1:16", version: "NVI" },
  { month: 11, day: 5, verseText: "porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.", verseReference: "Efésios 6:12", version: "ARC" },
  { month: 11, day: 6, verseText: "Considero, pois, que os sofrimentos do tempo presente não podem ser comparados com a glória que em nós será revelada.", verseReference: "Romanos 8:18", version: "NVI" },
  { month: 11, day: 7, verseText: "ele me ensinava e me dizia: \"Apegue-se às minhas palavras de todo o coração; obedeça aos meus mandamentos, e você terá vida.", verseReference: "Provérbios 4:4", version: "NVI" },
  { month: 11, day: 8, verseText: "Portanto, sejam imitadores de Deus, como filhos amados,", verseReference: "Efésios 5:1", version: "NVI" },
  { month: 11, day: 9, verseText: "Seja a atitude de vocês a mesma de Cristo Jesus,", verseReference: "Filipenses 2:5", version: "NVI" },
  { month: 11, day: 10, verseText: "\"Eu lhes asseguro: Quem ouve a minha palavra e crê naquele que me enviou, tem a vida eterna e não será condenado, mas já passou da morte para a vida.", verseReference: "João 5:24", version: "NVI" },
  { month: 11, day: 11, verseText: "Tu és o meu abrigo e o meu escudo; e na tua palavra depositei a minha esperança.", verseReference: "Salmos 119:114", version: "NVI" },
  { month: 11, day: 12, verseText: "Ele se entregou por nós a fim de nos remir de toda a maldade e purificar para si mesmo um povo particularmente seu, dedicado à prática de boas obras.", verseReference: "Tito 2:14", version: "NVI" },
  { month: 11, day: 13, verseText: "Perguntaram-se um ao outro: \"Não estavam ardendo os nossos corações dentro de nós, enquanto ele nos falava no caminho e nos expunha as Escrituras? \"", verseReference: "Lucas 24:32", version: "NVI" },
  { month: 11, day: 14, verseText: "\"Agora, eu os entrego a Deus e à palavra da sua graça, que pode edificá-los e dar-lhes herança entre todos os que são santificados.", verseReference: "Atos dos Apóstolos 20:32", version: "NVI" },
  { month: 11, day: 15, verseText: "Pois aqueles que de antemão conheceu, também os predestinou para serem conformes à imagem de seu Filho, a fim de que ele seja o primogênito entre muitos irmãos.", verseReference: "Romanos 8:29", version: "NVI" },
  { month: 11, day: 16, verseText: "que nos salvou e nos chamou com uma santa vocação, não em virtude das nossas obras, mas por causa da sua própria determinação e graça. Esta graça nos foi dada em Cristo Jesus desde os tempos eternos,", verseReference: "2 Timóteo 1:9", version: "NVI" },
  { month: 11, day: 17, verseText: "Em vez disso, esperavam eles uma pátria melhor, isto é, a pátria celestial. Por essa razão Deus não se envergonha de ser chamado o Deus deles, pois preparou-lhes uma cidade.", verseReference: "Hebreus 11:16", version: "NVI" },
  { month: 11, day: 18, verseText: "Pois quem quiser salvar a sua vida a perderá, mas quem perder a própria vida por minha causa a salvará.", verseReference: "Lucas 9:24", version: "NVI" },
  { month: 11, day: 19, verseText: "Novamente, Jesus disse: ― Paz seja com vocês! Como o Pai me enviou, assim eu os envio.", verseReference: "João 20:21", version: "NVI" },
  { month: 11, day: 20, verseText: "pois “todo aquele que invocar o nome do Senhor será salvo”.", verseReference: "Romanos 10:13", version: "NVI" },
  { month: 11, day: 21, verseText: "Ora, o Senhor é o Espírito e, onde está o Espírito do Senhor, ali há liberdade.", verseReference: "2 Coríntios 3:17", version: "NVI" },
  { month: 11, day: 22, verseText: "Quando a ansiedade já me dominava no íntimo, o teu consolo trouxe alívio à minha alma.", verseReference: "Salmos 94:19", version: "NVI" },
  { month: 11, day: 23, verseText: "Deem graças ao Senhor e invoquem o seu nome! Divulguem entre as nações o que ele tem feito!", verseReference: "Salmos 105:1", version: "NVI" },
  { month: 11, day: 24, verseText: "\"Felizes os que lavam as suas vestes, para que tenham direito à árvore da vida e possam entrar na cidade pelas portas.", verseReference: "Apocalipse 22:14", version: "NVI" },
  { month: 11, day: 25, verseText: "Se, porém, não lhes agrada servir ao Senhor, escolham hoje a quem irão servir, se aos deuses que os seus antepassados serviram além do Eufrates, ou aos deuses dos amorreus, em cuja terra vocês estão vivendo. Mas, eu e a minha família serviremos ao Senhor\".", verseReference: "Josué 24:15", version: "NVI" },
  { month: 11, day: 26, verseText: "Meus amados irmãos, tenham isto em mente: sejam todos prontos para ouvir, tardios para falar e tardios para irar‑se,", verseReference: "Tiago 1:19", version: "NVI" },
  { month: 11, day: 27, verseText: "Quem examina cada questão com cuidado, prospera, e feliz é aquele que confia no Senhor.", verseReference: "Provérbios 16:20", version: "NVI" },
  { month: 11, day: 28, verseText: "Levem os fardos uns dos outros e, assim, cumpram a lei de Cristo.", verseReference: "Gálatas 6:2", version: "NVI" },
  { month: 11, day: 29, verseText: "\"O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é entendimento.", verseReference: "Provérbios 9:10", version: "NVI" },
  { month: 11, day: 30, verseText: "Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbem os seus corações, nem tenham medo.", verseReference: "João 14:27", version: "NVI" },
  { month: 12, day: 1, verseText: "Pois vocês conhecem a graça de nosso Senhor Jesus Cristo que, sendo rico, se fez pobre por amor de vocês, para que por meio de sua pobreza vocês se tornassem ricos.", verseReference: "2 Coríntios 8:9", version: "NVI" },
  { month: 12, day: 2, verseText: "Contudo, aos que o receberam, aos que creram em seu nome, deu-lhes o direito de se tornarem filhos de Deus,", verseReference: "João 1:12", version: "NVI" },
  { month: 12, day: 3, verseText: "A aspiração da carne conduz à morte, mas a do Espírito conduz à vida e à paz;", verseReference: "Romanos 8:6", version: "NVI" },
  { month: 12, day: 4, verseText: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento;", verseReference: "Provérbios 3:5", version: "NVI" },
  { month: 12, day: 5, verseText: "Quando os caminhos de um homem são agradáveis ao Senhor, ele faz que até os seus inimigos vivam em paz com ele.", verseReference: "Provérbios 16:7", version: "NVI" },
  { month: 12, day: 6, verseText: "Portanto, não se preocupem com o amanhã, pois o amanhã trará as suas próprias preocupações. Bastam a cada dia os seus próprios problemas.", verseReference: "Mateus 6:34", version: "NVI" },
  { month: 12, day: 7, verseText: "Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige: Pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.", verseReference: "Miquéias 6:8", version: "NVI" },
  { month: 12, day: 8, verseText: "Os que pertencem a Cristo Jesus crucificaram a carne, com as suas paixões e os seus desejos.", verseReference: "Gálatas 5:24", version: "NVI" },
  { month: 12, day: 9, verseText: "bendigam aqueles que os maldizem, orem por aqueles que os maltratam.", verseReference: "Lucas 6:28", version: "NVI" },
  { month: 12, day: 10, verseText: "Jesus dizia a todos: \"Se alguém quiser acompanhar-me, negue-se a si mesmo, tome diariamente a sua cruz e siga-me.", verseReference: "Lucas 9:23", version: "NVI" },
  { month: 12, day: 11, verseText: "Todo aquele que não permanece no ensino de Cristo, mas vai além dele, não tem Deus; quem permanece no ensino tem o Pai e também o Filho.", verseReference: "2 João 1:9", version: "NVI" },
  { month: 12, day: 12, verseText: "Mas o que para mim era lucro, passei a considerar perda, por causa de Cristo.", verseReference: "Filipenses 3:7", version: "NVI" },
  { month: 12, day: 13, verseText: "O Senhor é o meu pastor; de nada terei falta", verseReference: "Salmos 23:1", version: "NVI" },
  { month: 12, day: 14, verseText: "Tragam o dízimo todo ao depósito do templo, para que haja alimento em minha casa. Ponham-me à prova\", diz o Senhor dos Exércitos, \"e vejam se não vou abrir as comportas dos céus e derramar sobre vocês tantas bênçãos que nem terão onde guardá-las.", verseReference: "Malaquias 3:10", version: "NVI" },
  { month: 12, day: 15, verseText: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", verseReference: "1 Coríntios 13:4", version: "NVI" },
  { month: 12, day: 16, verseText: "Em paz me deito e logo adormeço, pois só tu, Senhor , me fazes viver em segurança.", verseReference: "Salmos 4:8", version: "NVI" },
  { month: 12, day: 17, verseText: "Quem fez tudo isso? Quem chama as gerações à existência desde o princípio? Fui eu mesmo, o Senhor, o primeiro, que continuarei sendo, até mesmo com os últimos. \"", verseReference: "Isaías 41:4", version: "NVI" },
  { month: 12, day: 18, verseText: "Portanto, submetam‑se a Deus. Resistam ao Diabo, e ele fugirá de vocês.", verseReference: "Tiago 4:7", version: "NVI" },
  { month: 12, day: 19, verseText: "Cantarei para sempre os atos de amor leal do SENHOR; com a minha boca anunciarei a tua fidelidade por todas as gerações.", verseReference: "Salmos 89:1", version: "NVI" },
  { month: 12, day: 20, verseText: "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.", verseReference: "Salmos 34:18", version: "NVI" },
  { month: 12, day: 21, verseText: "Da mesma forma o Espírito nos ajuda em nossa fraqueza, pois não sabemos como orar, mas o próprio Espírito intercede por nós com gemidos inexprimíveis.", verseReference: "Romanos 8:26", version: "NVI" },
  { month: 12, day: 22, verseText: "Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.", verseReference: "1 João 1:9", version: "NVI" },
  { month: 12, day: 23, verseText: "Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus\".", verseReference: "Mateus 5:16", version: "NVI" },
  { month: 12, day: 24, verseText: "Portanto, meus amados irmãos, mantenham-se firmes, e que nada os abale. Sejam sempre dedicados à obra do Senhor, pois vocês sabem que, no Senhor, o trabalho de vocês não será inútil.", verseReference: "1 Coríntios 15:58", version: "NVI" },
  { month: 12, day: 25, verseText: "Porque um menino nos nasceu, um filho nos foi dado, e o governo está sobre os seus ombros. E ele será chamado Maravilhoso Conselheiro, Deus Poderoso, Pai Eterno, Príncipe da Paz.", verseReference: "Isaías 9:6", version: "NVI" },
  { month: 12, day: 26, verseText: "quem afirma que permanece nele deve andar como ele andou.", verseReference: "1 João 2:6", version: "NVI" },
  { month: 12, day: 27, verseText: "Sobretudo, amem sinceramente uns aos outros, porque o amor perdoa uma multidão de pecados.", verseReference: "1 Pedro 4:8", version: "NVI" },
  { month: 12, day: 28, verseText: "Bem-aventurados os que têm fome e sede de justiça, pois serão satisfeitos.", verseReference: "Mateus 5:6", version: "NVI" },
  { month: 12, day: 29, verseText: "Então Jesus lhe disse: \"Porque me viu, você creu? Felizes os que não viram e creram\".", verseReference: "João 20:29", version: "NVI" },
  { month: 12, day: 30, verseText: "Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei, o qual é a salvação da minha face, e o meu Deus.", verseReference: "Salmos 42:11", version: "ACF" },
  { month: 12, day: 31, verseText: "Todo o que o Pai me der virá a mim, e quem vier a mim eu jamais rejeitarei.", verseReference: "João 6:37", version: "NVI" },
];

async function main() {
  console.log('Iniciando o processo de seed...');

  await prisma.dailyVerse.deleteMany({});
  console.log('Tabela de versículos diários limpa.');

  if (verses.length === 0) {
    console.log('Nenhum versículo para adicionar. Encerrando o seed.');
    return;
  }

  await prisma.dailyVerse.createMany({
    data: verses,
  });
  console.log(`Foram criados ${verses.length} registros de versículos.`);
  console.log('Seed finalizado com sucesso!');
}

main()
  .catch((e) => {
    console.error("Ocorreu um erro durante a execução do seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    console.log("Desconectando o Prisma...");
    await prisma.$disconnect();
  });